const uid = () => Math.random().toString(36).slice(2, 10);

export const CATEGORIES = [
  "Housing",
  "Food & Dining",
  "Transport",
  "Shopping",
  "Healthcare",
  "Entertainment",
  "Utilities",
  "Income",
  "Freelance",
  "Investment",
];

export const CATEGORY_COLORS = {
  Housing: "#7c6ff7",
  "Food & Dining": "#f87171",
  Transport: "#34d399",
  Shopping: "#fbbf24",
  Healthcare: "#60a5fa",
  Entertainment: "#f472b6",
  Utilities: "#a78bfa",
  Income: "#10b981",
  Freelance: "#06b6d4",
  Investment: "#8b5cf6",
};

export const mockTransactions = [
  // --- January ---
  {
    id: uid(),
    date: "2025-01-03",
    description: "Salary Deposit",
    category: "Income",
    amount: 4500,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-01-04",
    description: "Rent Payment",
    category: "Housing",
    amount: 1400,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-06",
    description: "Grocery Store",
    category: "Food & Dining",
    amount: 124,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-09",
    description: "Netflix",
    category: "Entertainment",
    amount: 15,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-11",
    description: "Uber Ride",
    category: "Transport",
    amount: 22,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-14",
    description: "Electricity Bill",
    category: "Utilities",
    amount: 85,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-17",
    description: "Freelance Project",
    category: "Freelance",
    amount: 800,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-01-20",
    description: "Pharmacy",
    category: "Healthcare",
    amount: 45,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-22",
    description: "Amazon Purchase",
    category: "Shopping",
    amount: 139,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-25",
    description: "Gym Membership",
    category: "Healthcare",
    amount: 40,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-01-28",
    description: "Stock Dividend",
    category: "Investment",
    amount: 220,
    type: "income",
  },

  // --- February ---
  {
    id: uid(),
    date: "2025-02-01",
    description: "Salary Deposit",
    category: "Income",
    amount: 4500,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-02-03",
    description: "Rent Payment",
    category: "Housing",
    amount: 1400,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-05",
    description: "Restaurant Dinner",
    category: "Food & Dining",
    amount: 78,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-07",
    description: "Spotify",
    category: "Entertainment",
    amount: 10,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-10",
    description: "Bus Pass",
    category: "Transport",
    amount: 60,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-12",
    description: "Water Bill",
    category: "Utilities",
    amount: 40,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-15",
    description: "Freelance Project",
    category: "Freelance",
    amount: 1200,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-02-18",
    description: "Doctor Visit",
    category: "Healthcare",
    amount: 120,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-20",
    description: "Clothing Store",
    category: "Shopping",
    amount: 210,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-24",
    description: "Grocery Store",
    category: "Food & Dining",
    amount: 98,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-02-26",
    description: "Stock Dividend",
    category: "Investment",
    amount: 180,
    type: "income",
  },

  // --- March ---
  {
    id: uid(),
    date: "2025-03-01",
    description: "Salary Deposit",
    category: "Income",
    amount: 4500,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-03-02",
    description: "Rent Payment",
    category: "Housing",
    amount: 1400,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-04",
    description: "Grocery Store",
    category: "Food & Dining",
    amount: 145,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-06",
    description: "Uber Ride",
    category: "Transport",
    amount: 18,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-08",
    description: "Amazon Purchase",
    category: "Shopping",
    amount: 89,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-10",
    description: "Netflix",
    category: "Entertainment",
    amount: 15,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-12",
    description: "Electricity Bill",
    category: "Utilities",
    amount: 92,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-15",
    description: "Freelance Project",
    category: "Freelance",
    amount: 1500,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-03-18",
    description: "Pharmacy",
    category: "Healthcare",
    amount: 35,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-22",
    description: "Restaurant Dinner",
    category: "Food & Dining",
    amount: 64,
    type: "expense",
  },
  {
    id: uid(),
    date: "2025-03-25",
    description: "Stock Dividend",
    category: "Investment",
    amount: 260,
    type: "income",
  },
  {
    id: uid(),
    date: "2025-03-28",
    description: "Gym Membership",
    category: "Healthcare",
    amount: 40,
    type: "expense",
  },
];

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
